config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' =>'epicenter#now_following'

  get 'unfollow' =>'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' =>	'epicenter#followers'

  resources :tweets
  devise_for :users

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create

	validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 characters.  This isn't Facebook!"}, on: :create
	after_validation :apply_link, on: :create

	private

	def link_check
		check = false
		if self.message.include?("http://") || self.message.include?("https://") || self.message.include?("www")
			check = true
		end
		
		if check == true
			arr = self.message.split

			if self.message.include?("http") 
				index = arr.map{|x| x.include?"http"}.index(true) 
				self.link = arr[index]
			elsif self.message.include?("www")
				index = arr.map{|x| x.include?"www"}.index(true)
				self.link = "http://#{arr[index]}"
			end		

		
			if arr[index].length > 23
				arr[index] = "#{arr[index][0..19]}..."
			end
			
			self.message = arr.join(" ")	
		end		
	end	

	def apply_link
		arr = self.message.split

		if self.message.include?("http")
			index = arr.map{|x| x.include?"http"}.index(true)
		elsif self.message.include?("www")
			index = arr.map{|x| x.include?"www"}.index(true)
		end		

		if index
			url = arr[index]
			arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
		end
		
		self.message = arr.join(" ")	
	end	


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:show, :index]

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_arr = tweet.message.split
    message_arr.each_with_index do |word, index|
      if word[0] == "#"
        if Tag.pluck(:phrase).include?(word.downcase)
          tag = Tag.find_by(phrase: word.downcase)
        else
          tag = Tag.create(phrase: word.downcase)
        end 
        tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id) 
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>" 
      end 
    end 
		tweet.message = message_arr.join(" ") 
		return tweet  
	end	




end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  

  <div class="form-group">
    <%= form.text_field :message, placeholder: "What's on your mind?", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Tweet it!", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th>Profile Pic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td>@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= image_tag tweet.user.avatar.thumb %></td>
        <td><%= link_to 'Show', tweet %></td>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<center>
	<div>
		<%=  image_tag @tweet.user.avatar.show, class: "img-circle" %>
	</div>

	<br/>
<div class="well">
	<p>
	  On <%=  @tweet.created_at.strftime('%B %e, %Y at %l:%M %P') %>, @<%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %> said...
	</p>
	<p>
	  
	  <%= @tweet.message.html_safe %>
	</p>
</div>
</center>
<% if user_signed_in? && current_user.id == @tweet.user_id %>
	<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<% end %>
<%= link_to 'Back', tweets_path %>