config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' =>'epicenter#now_following'

  get 'unfollow' =>'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' =>	'epicenter#followers'

  resources :tweets
  devise_for :users

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  def feed
      @tweet = Tweet.new
      @following_tweets =[]

      Tweet.all.each do |tweet|
        if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
          @following_tweets.push(tweet)
        end
      end 
  


  	# if user_signed_in?
	  # 	@following_tweets =[]

	  # 	Tweet.all.each do |tweet|
	  # 		if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
	  # 			@following_tweets.push(tweet)
	  # 		end
	  # 	end	
	  # else
	  # 	redirect_to tweets_path
	  # end	
	end

  def show_user
    @tweet = Tweet.new
  	@user = User.find(params[:id])
  end

  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end


  def tag_tweets
    @tag = Tag.find(params[:id])
  end  


  def all_users
    @users = User.all
  end 

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end 

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end 

end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/views/epicenter/_user_list.html.erb
<div class="row">
	<% @users.each do |user| %>
		<div class="col-lg-6">
			<div class="well profiles-page">
				<center>
					<div>
					<%= image_tag user.avatar.thumb, class: "img-circle" %>
					</div>
					<h5><%=  link_to  user.username, show_user_path(id: user.id) %></h5>
					<p>Name: <%=  link_to  user.name, show_user_path(id: user.id) %></p>
					<p>Home: <%= user.location %></p>
					<p>About: <%= user.bio %></p>
					<p><%= link_to "Following", following_path(id: user.id) %></p>
					<p><%= link_to "Followers", followers_path(id: user.id) %></p>

					<p>
				    <% if current_user.following.include?(user.id) %>
				        <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary unfollow_btn" %>
				    <% else %>
				        <% if current_user.id != user.id %>
					    		<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
					    	<% end %>	
				  	<% end %>
					</p>
				</center>
			</div>
		</div>
	<% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>These are all the current Users:</h1>

<div>
	<%= render 'user_list' %>
</div>

app/views/epicenter/feed.html.erb
<center><h3>Welcome @<%= current_user.username %>!  Here is your feed.</h3>
<p>See what your "friends" are talking about!</p></center>
<div>
	<%= render 'tweets/form', tweet: @tweet %>
</div>
	

<div class="well">
	<% @following_tweets.each do |tweet| %>
		<div class="media">
		  <div class="media-left">
		      <%= image_tag tweet.user.avatar.thumb, class: 'img-circle' %>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading">@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %> • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %><%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at > 86400 %></h4>
		    <p><%= tweet.message.html_safe %></p>
		  </div>
		</div>
	<% end %>
</div>

app/views/epicenter/followers.html.erb
<h3>Here's who is following <%= @user.username %>:  </h3>

<div>
	<%= render 'user_list' %>
</div>

app/views/epicenter/following.html.erb
<h3>Here's who <%= @user.username %> is following: </h3>

<div>
	<%= render 'user_list' %>
</div>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<center>
	<h1>@<%= @user.username %>'s profile page</h1>


	<div>
		<%= image_tag @user.avatar.show, class: "img-circle" %>
	</div>
	<p>Name: <%=  @user.name %></p>
	<p>Location; <%= @user.location %></p>
	<p>Bio: <%= @user.bio %></p>


	<p>
    <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary unfollow_btn" %>
    <% else %>
        <% if current_user.id != @user.id %>
	    		<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>

	    	<% else %>
	    		<%= render 'tweets/form', tweet: @tweet %>
				<% end %>
  	<% end %>
</p>
</center>

<div class="well">
	<% @user.tweets.each do |tweet| %>
		<div class="media">
		  <div class="media-left">
		      <%= image_tag tweet.user.avatar.thumb, class: 'img-circle' %>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading">On <%=  tweet.created_at.strftime('%B %e, %Y at %l:%M %P') %>, @<%= tweet.user.username %> said...</h4>
		    <p><%= tweet.message.html_safe %></p>
		  </div>
		</div>
	<% end %>
</div>

app/views/epicenter/tag_tweets.html.erb
<h3>Here's what people are saying about <strong><%= @tag.phrase %></strong>:</h3>


	<% @tag.tweets.each do |tweet| %>
		<div class="well">
			<p><%= image_tag tweet.user.avatar.thumb %> <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %> • <%= time_ago_in_words(tweet.created_at) %></p>
			<p><%= tweet.message.html_safe %></p>
		</div>	
	<% end %>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>