config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' =>'epicenter#now_following'

  get 'unfollow' =>'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' =>	'epicenter#followers'

  resources :tweets
  devise_for :users

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jun2018SocialMediaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- begin of navbar -->
  	<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Your Feed", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        	<li><%= link_to "All Tweets", tweets_path %></li>
          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
          <li><%= link_to "All Users", all_users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.blank? == false %>
                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                <% end %> 
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
            	<li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  	<!-- end of navbar -->


  	<div class="container">
  	<div class="row">

  		<!-- The area for our stats -->
  		<div class="col-lg-3">
  			<div class="well">
	  			<div class="user-stats">
		  				<% if user_signed_in? %>
			  				<%= image_tag current_user.avatar.show, class: "img-circle" %>
			  				<h5><%= current_user.name %></h5>
			  				<p>@<%= current_user.username %></p>
			  				<p>Location: <%= current_user.location %></p>
			  				<p><%= current_user.bio %></p>
                <p>Following: <%= link_to current_user.following.count, following_path(id: current_user.id)  %> | Followers: <%= link_to get_followers(current_user.id), followers_path(id: current_user.id) %> </p>

			  			<% else %>	
			  			  <h5>Sign in to be a part of the conversation!</h5>
			  			<% end %>
	  			</div>
	  		</div>
	  	</div>
	  	<!-- The area for our other pages -->
  			<div class="col-lg-6 well">	
			    <%= yield %>
			  </div>

			<!-- The area for what's trending -->
   
  		  <div class="col-lg-3">
    			<div class="well">
  	  			<h3>What's Trending!</h3>
             <% hot_tags.each do |tag| %>
                <%= link_to tag.phrase, tag_tweets_path(id: tag.id) %>
              <% end %>
          <% if user_signed_in? %>
              <h3>Hottest Tweeter:</h3>
              <p><%= image_tag top_tweeter.avatar.show, class: "img-circle" %></p>
              <p><%= link_to "@#{top_tweeter.username}", show_user_path(id: top_tweeter.id) %> with <%= top_number_tweets(top_tweeter.id) %> tweets!</p>
            <% end %>
          </div>
  	  	</div>
      
	  	</div>

		</div>
	</div>
  </body>
</html>